language: go
go:
- stable
deploy:
- provider: script
  skip_cleanup: true
  script: bash scripts/release.sh
  on:
    repo: NoUseFreak/wait-for-it
    branch: master
    tags: true
env:
  global:
    secure: bxZ1Wbijg7oIv6uE3/lE7XTqxmU+jGDDFwuPjsVoJjbP+gN4Dkn5yFZnPhAdeER0r/Dd4nHFSxHd1IcOL4WMNhDg/dJT9EoFtyuAZLMd1rxWAuUL+Cojn/MrGHBkg+Xs7dkhL7FS7ZQz09SmpMZEWyNSStPzMu1TNj4co0+Wk2QEFfGIYWpe408+psHu61XUbcwnieYi1HTpT/VNqi82Uik2QIc937EQRR3n3ciy8NFxCmJFzR0UTXf5rzbqUACX7HmTvHlpsu1C6M4zZo8LXHhdzyNT9ml3m46ULCAH37OiPx8TfZG/kXqlpfPzJv150l3/SRaS7MtrK5hB892RvidevIIHpGOt5twjMvIei7aTVsNx1E+2GKvla12t//fxabjrijXH9MGfQ/vDgkk4ZXdq0ENpP4z8/ARQWUmkG/WQVIka/aTcg4cYHDIrQp5FEzBN365UfH7q2E9Chh7s49vaJ9OuSgW5J7PUiNwcClNeV02ovUNm7acKQ+H/XJGCNE2dlValvoIDQWZHoef+Wc/EZKDJfPNjdNCe4Drg/BcGUIm6/FCEA+L5Wblow0eV3XAem7FsNmU6k9z6k2KUGAwOXR93d112J8seXj1O1UxpOu3gUR9O6B/7ILcNGeEpcNKh4Ndw7AQXV4JhuhY8b6JV3gVogO5szDqa6+y5tis=
