version: '3'
services:
  mysql:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
  redis:
    image: redis
    ports:
      - 6379:6379
  cassandra:
    image: cassandra
    ports:
      - 9042:9042
