version: '3'
services:
  mysql:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
  redis:
    image: redis
    ports:
      - 6379:6379
  cassandra:
    image: cassandra
    ports:
      - 9042:9042
  kafka:
    image: spotify/kafka
    ports:
      - 2181:2181
      - 9092:9092
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
